# Steel Power Prediction Project Configuration
# Current Date and Time (UTC): 2025-02-26 14:45:24
# Current User: XC

project:
  name: steel_power_prediction
  version: 0.1.0
  description: 基于深度强化学习的钢铁厂电力需求预测系统
  created_at: '2025-02-25 05:31:30'
  updated_at: '2025-02-26 14:45:24'
  created_by: zlbbbb
  updated_by: XC
data:
  paths:
    raw: data/raw/steel_industry_data.csv
    processed: data/processed
    interim: data/processed/interim
    features: data/processed/features
    final: data/processed/final
  split:
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
  sequence_length: 24
  prediction_horizon: 12
  features:
    numerical:
    - name: Usage_kWh
      type: float
      normalization: standard
      handle_missing: interpolate
      outlier_detection: true
      outlier_method: IQR
      outlier_threshold: 1.5
    - name: Lagging_Current_Reactive.Power_kVarh
      type: float
      normalization: standard
    - name: Leading_Current_Reactive_Power_kVarh
      type: float
      normalization: standard
    - name: CO2(tCO2)
      type: float
      normalization: standard
    - name: Lagging_Current_Power_Factor
      type: float
      normalization: minmax
    - name: Leading_Current_Power_Factor
      type: float
      normalization: minmax
    categorical:
    - name: WeekStatus
      type: category
      encoding: onehot
    - name: Day_of_week
      type: category
      encoding: onehot
    - name: Load_Type
      type: category
      encoding: onehot
  preprocessing:
    handle_missing: interpolate
    outlier_detection: true
    outlier_method: IQR
    normalization: standard
    validation:
      check_missing: true
      check_duplicates: true
      check_data_types: true
      check_value_ranges: true
  feature_engineering:
    time_features:
    - hour
    - day_of_week
    - month
    - is_weekend
    rolling_features:
      window_sizes:
      - 6
      - 12
      - 24
      operations:
      - mean
      - std
      - min
      - max
    lag_features:
      lag_hours:
      - 1
      - 2
      - 3
      - 6
      - 12
      - 24
model:
  type: DQN
  network:
    hidden_size:
    - 256
    - 128
    - 64
    dropout: 0.1
    activation: relu
    batch_norm: true
    initialization: kaiming
  dqn:
    learning_rate: 0.0005
    gamma: 0.99
    memory_size: 10000
    batch_size: 64
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995
    target_update: 10
    use_dueling: true
    use_double: true
    use_priority: false
    clip_grad_norm: 1.0
    optimizer: adam
    scheduler:
      type: reduce_on_plateau
      patience: 5
      factor: 0.5
      min_lr: 1.0e-05
  learning_rate: 0.0005
  batch_size: 64
training:
  epochs: 1000
  max_steps: 500
  eval_frequency: 10
  save_frequency: 50
  seed: 42
  device: cuda
  num_workers: 4
  early_stopping:
    enabled: true
    patience: 20
    min_delta: 0.0001
    monitor: episode_reward
    mode: max
  checkpoint:
    enabled: true
    dir: checkpoints
    load: false
    save_best: true
    save_last: true
    save_frequency: 50
    max_keep: 5
  logging:
    level: INFO
    dir: logs
    tensorboard: true
    log_frequency: 100
    metrics:
    - episode_reward
    - average_loss
    - epsilon
    - episode_length
    - predicted_power
    - actual_power
    - prediction_error
environment:
  state_size: 24
  action_size: 100
  power:
    max: 10000
    min: 0
    scaling_factor: 0.001
  rewards:
    scale: 1.0
    shaping: true
    done_penalty: -100
    success_reward: 100
    step_penalty: -1
    error_threshold: 0.2
    reward_weights:
      error_weight: 0.6
      smoothness_weight: 0.2
      trend_weight: 0.2
evaluation:
  num_episodes: 100
  batch_size: 32
  model_path: checkpoints/best_model.pth
  output_dir: reports/evaluation
  save_predictions: true
  metrics:
  - name: mse
    enabled: true
  - name: rmse
    enabled: true
  - name: mae
    enabled: true
  - name: mape
    enabled: true
  - name: r2
    enabled: true
  visualization:
    enabled: true
    save_plots: true
    show_plots: false
    style: seaborn
    dpi: 300
    plots:
      predictions:
        enabled: true
        style: line
        filename: prediction_results.png
        confidence_interval: true
      error_dist:
        enabled: true
        style: hist
        filename: error_distribution.png
        bins: 50
      training_curves:
        enabled: true
        metrics:
        - loss
        - reward
        - epsilon
        filename: training_curves.png
        rolling_window: 10
      feature_importance:
        enabled: true
        filename: feature_importance.png
        method: shap
debug:
  enabled: false
  verbose: false
  profile: false
  save_memory_usage: false
  max_warnings: 100
